apiVersion: v1
kind: Service
metadata:
  name: itdt-frontend-service
spec:
  selector:
    app: itdt-frontend
  type: NodePort
  ports:
  - protocol: TCP
    port: 3010
    name: frontend-port
    targetPort: frontend-port
